version: '3'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: jeedom
       MYSQL_DATABASE: jeedom
       MYSQL_USER: jeedom
       MYSQL_PASSWORD: jeedom
     networks:
       dedicated:
         aliases:
            - database
            
     container_name: jeedom-database

   server:
     image: jeedom/jeedom:stable
     links:
       - db
     ports:
       - 80:80
       - 443:443
     restart: always
     environment:
       ROOT_PASSWORD: ${JEEDOM_ROOT_PASSWORD}
     volumes:
      - data:/var/www/html
     tmpfs:
      - /var/www/html/log
      - /tmp/jeedom/cache      
      - /tmp/jeedom/backup
     network_mode: host
     container_name: jeedom
     networks:
      - dedicated
      external:
         name: host
      
networks:
  dedicated:
  
volumes:
    db_data:
    data:
