version: '3.5'

services:
   db:
     image: mysql/mysql-server:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: jeedom
       MYSQL_DATABASE: jeedom
       MYSQL_USER: jeedom
       MYSQL_PASSWORD: jeedom          
     container_name: jeedom-database
     networks:
       dedicated:
         aliases:
            - database

   server:
     image: jeedom/jeedom:latest
#     links:
#       - "db:database"
     ports:
       - 80:80
     restart: always
     environment:
       ROOT_PASSWORD: ${JEEDOM_ROOT_PASSWORD}
     volumes:
      - data:/var/www/html
     tmpfs:
      - /var/www/html/log
      - /tmp/jeedom/cache      
      - /tmp/jeedom/backup
     container_name: jeedom
     command: "sed -i 's/max_execution_time = 300/max_execution_time = 600/g' /etc/php/7.0/apache2/php.ini"
     networks:
       - dedicated
       - forbroad
     
networks:
  dedicated:
  forbroad:
    external:
      name: vlan_home_automation

#   cache:
#    image: memcached:alpine
#     links:
#      - server
#    restart: always
#    container_name: jeedom-memcached
#    networks:
#     - dedicated  
      
volumes:
    db_data:
    data:
