version: '3'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: jeedom
       MYSQL_USER: jeedom
       MYSQL_PASSWORD: jeedom
     networks:
         jeedom-dedicated:
           aliases:
            - database
            
     container_name: jeedom-database

   jeedom:
     image: jeedom/jeedom:latest
     links:
       - db
     ports:
       - 80:80
       - 443:443
     restart: always
     environment:
       ROOT_PASSWORD: ${JEEDOM_ROOT_PASSWORD}
     volumes:
      - data:/var/www/html
      - backup:/mnt/backup
     network_mode: host
     container_name: jeedom
     networks:
      - jeedom-dedicated
     devices:
      - /dev/bus/usb/001/004:/dev/ttyacm0
      
networks:
  jeedom-dedicated:
  
volumes:
    db_data:
    data:
    backup:
